name = "CoverageTools"
uuid = "c36e975a-824b-4404-a568-ef97ca766997"
version = "1.4.1"
authors = ["Iain Dunning <iaindunning@gmail.com>", "contributors"]

[deps]
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
JuliaSyntax = "1,2"
TOML = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
