name = "CoverageTools"
uuid = "c36e975a-824b-4404-a568-ef97ca766997"
authors = ["Iain Dunning <iaindunning@gmail.com>", "contributors"]
version = "1.3.2"

[deps]
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"

[compat]
julia = "1"
JuliaSyntax = "0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
